meson.build, src/libxmlb/meson.build
Meson 0.47 introduces copy kwarg [1] to configure_file, allowing us to copy files to build directory in a slightly cleaner way than passing an empty configuration_data() object.
It is still a hack before install_headers can copy files to subdir in the build directory. [2]
[1]: http://mesonbuild.com/Reference-manual.html#configure_file
[2]: https://github.com/mesonbuild/meson/issues/2546
=> meson: Copy headers using copy kwarg

src/xb-machine.c
Include a local copy of g_ascii_string_to_unsigned() to avoid raising the GLib
dep to what's available in Ubuntu 16.04.
Fixes https://github.com/hughsie/libxmlb/issues/3
@superm1 -- can you try this without too much work? If it makes it easier, feel free to cherry pick onto wip/subproject
=> Fix compiling on Ubuntu Xenial

meson.build, src/generate-version-script.py, src/meson.build
Most *BSD systems don't consider python as an integral part of the
operating system, so python is seldom installed in /usr prefix.
This fixes gnome-software build on FreeBSD:
```
[38/259] Generating libxmlb-mapfile with a custom command.
FAILED: subprojects/libxmlb/src/libxmlb.map
/home/lantw44/gnome/source/gnome-software/subprojects/libxmlb/src/generate-version-script.py LIBXMLB subprojects/libxmlb/src/Xmlb-1.0.gir subprojects/libxmlb/src/libxmlb.map
/bin/sh: /home/lantw44/gnome/source/gnome-software/subprojects/libxmlb/src/generate-version-script.py: not found
```
=> Don't hardcode the path of python3

src/xb-builder.c, src/xb-builder.h
This allows us to load from a silo without caring about the exact GUID.
This may be useful if the cache keys are not the same for some reason.
=> Add XB_BUILDER_COMPILE_FLAG_IGNORE_GUID

data/meson.build
The tests themselves are only installed when requested, and so should
the test data.
=> build: Conditionalize installation of test data

contrib/ci/Dockerfile-debian, contrib/ci/Dockerfile-fedora, meson.build
Meson helpfully complains about the fact we required 0.46.0 but used
features only available in 0.50.0:
WARNING: Project targetting '>=0.47.0' but tried to use feature introduced in '0.50.0': install arg in configure_file
This requires updating the CI to Fedora 30, which seems like a good idea anyway.
=> build: Update the required version of Meson

.travis.yml, contrib/ci/Dockerfile-debian, contrib/ci/Dockerfile-fedora
This pull request makes the CI a bit nicer:
1. it removes an unnecessary operation from the Docker files;
2. it makes the jobs run in parallel on Debian and Fedora;
The most significant change is the latter, because it means testing libxmlb on other distros won't take longer to run, if everything runs in parallel.
=> A couple of CI improvements

.travis.yml, contrib/ci/Dockerfile-fedora, contrib/ci/check-abi
This adds a script which can check for ABI breaks between two Git
revisions:
$ ./contrib/ci/check-abi.sh ${OLD} ${NEW}
The CI is set up to run it automatically between the tip of the branch
being tested and the last release tag.
---
A couple of notes:
1.  this assumes tags are used only for releases, and compares the ABI of the branch being tested (in a pull request) to the last release tag; is that a fair assumption? Would you prefer comparing to master?
2.  it runs automatically in the CI, but you can also run it manually;
3.  if there's an ABI change libabigail thinks can break apps, it will fail the CI; you could then decide to merge anyway I guess, if you know it isn't an actual breakage?
On that note, libabigail sometimes reports false positives. As I said on IRC, Dodji loves [bug …
=> ci: Verify we don't break the ABI

data/libxmlb.test.in, data/meson.build, meson.build, src/meson.build
It is slightly cleaner and also it will be much easier for us to patch libxmlb to install them to a separate prefix.
It also fixes the issue that `INSTALLEDTESTDIR` was set to just `share/installed-tests/libxmlb` instead of the proper full path.
=> trivial: use variables for installed tests paths

contrib/ci/Dockerfile-debian, contrib/ci/Dockerfile-fedora, contrib/libxmlb.spec.in, meson.build, src/xb-builder.c, src/xb-silo-private.h, src/xb-silo.c, src/xb-string-private.h, src/xb-string.c
We can drop a difficult-to-use dep using built-in methods. We don't actually
have to create a RFC4122-compliant UUID as we're only using this for checking
file validity, and the extra few bits of the HMAC should be useful.
=> Do not use libuuid

src/libxmlb.map, src/xb-builder-source.c, src/xb-builder-source.h
This new function allows to specify an output_content_type for an
adapter in order to avoid sniffing mime types when that is not possible.
=> Add xb_builder_source_add_simple_adapter

contrib/libxmlb.spec.in, docs/libxmlb.types, meson.build, src/libxmlb.map, src/xb-machine.c, src/xb-machine.h, src/xb-opcode-private.h, src/xb-opcode.c, src/xb-opcode.h, src/xb-self-test.c, src/xb-silo.c, src/xb-stack-private.h, src/xb-stack.c, src/xb-stack.h
On a simple test of loading gnome-software and switching between a couple of
categories, this reduces calls to `g_slice_new0()` from around 21 million to
around 5 million.
It reduces the time to show (refine) the ‘Games’ category from around 9s to
around 5s the first time it’s shown (in a very unrigorous test).
This makes `XbOpcode` stack-only, and removes all API which requires it to be
heap-allocated. For the most part, this only requires mechanical changes in the
rest of the codebase to operate on stack-allocated opcodes, removing one layer
of indirection in some places.
The largest other change needed was to rewrite the optimiser to avoid using
`GArray`, as tracking the ownership of `XbOpcode`s through several different
`GArray`s was getting too complex. The new implementation of the …
=> Do not allocate opcodes individually

src/xb-builder-node.c, src/xb-builder.c
See the commit messages. tl;dr: This drops 17.4MB of heap allocations of empty `GPtrArray`s which never get used. (That’s about 833000 `GPtrArray` instances.) This reduces the peak memory consumption of gnome-software when it’s rebuilding its xmlb caches.
=> Eliminate unnecessary GPtrArray allocations in XbBuilderNode

src/xb-builder-fixup.c, src/xb-builder-node.c, src/xb-builder-source-ctx.c, src/xb-builder-source.c, src/xb-builder.c, src/xb-machine.c, src/xb-node.c, src/xb-query.c, src/xb-silo.c
The `parent_instance` member is only needed when creating a derived
`GObject` without a separate private data struct (for example, when
using `G_DECLARE_FINAL_TYPE`).
When using `G_DEFINE_TYPE_WITH_PRIVATE` the `MyTypePrivate` struct only
needs to contain the private members, no boilerplate.
This saves around 500KB of memory in the `XbNode`s created by the silo
when opening gnome-software.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
=> xb: Drop redundant parent_instance members from GObject private structs

src/xb-builder-source.h, src/xb-builder.c, src/xb-silo.c
See the commit messages.
tl;dr: This reduces the number of file monitors in gnome-software by an order of magnitude.
=> Allow monitoring directories as builder sources

src/xb-builder-node.c
If we ignore a node due to XB_BUILDER_COMPILE_FLAG_SINGLE_LANG then also ignore
the child nodes. This ensures we do not warn when presented with something like:
<description xml:lang=de>
<ul><li xml:lang=de></li><li></li></ul>
</description>
<description>
<ul><li></li></ul>
</description>
Fixes https://github.com/hughsie/libxmlb/issues/50
=> Do not show a critical warning for invalid XML

src/xb-builder-node.c
Since commit d12765d0, `priv->children` is loaded lazily, and can be
`NULL`. Commit b7f2509c2b3 (#50) introduced a crash in that case.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
=> xb-builder-node: Don’t crash if priv->children is NULL

src/libxmlb.map, src/xb-builder.c, src/xb-builder.h, src/xb-node-query.c, src/xb-node.c, src/xb-silo-export-private.h, src/xb-silo-export.c, src/xb-silo-query-private.h, src/xb-silo-query.c, src/xb-silo.c, src/xb-silo.h
See the commit messages for reasoning.
tl;dr: This drops 1.8MB of heap memory of `XbNode`s which are used a few times and then never used again, but hang around in the silo’s cache for the lifetime of gnome-software.
=> Conditionally drop XbSilo node cache

src/xb-builder.c, src/xb-self-test.c
We don't handle GMarkupParser->passthrough and so in the double-comment case we
can call GMarkupParser->text on the same builder node more than once. As it's
typically just a (another!) newline, just store the 'last set' tail rather than
trying to append them together.
Fixes https://github.com/hughsie/libxmlb/issues/70
=> Fix a parse failure for a double comment

src/xb-node.h, src/xb-self-test.c, src/xb-silo-export.c
Add a new COLLAPSE_IF_NO_CHILDREN flag to allow requesting collapsed
open/close tags (e.g. <collapsed/>) when exporting the XML.
=> Allow collapsing empty XML tags if no children or text

meson.build, src/xb-silo.c
It was only introduced in GLib 2.62, which isn’t available on (for
example) Debian Stable. Use the `g_rw_lock_*()` methods directly
instead. There’s no point in using `GRWLockReaderLocker` if the GLib
version is high enough, as the amount of macro boilerplate needed would
be relatively high.
This fixes building gnome-software (transitively) on Debian Stable.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
=> xb-silo: Don’t use GRWLockReaderLocker yet

src/xb-query-context.c, src/xb-value-bindings.c
Unfortunately it’s not protected by `GLIB_VERSION_MAX_ALLOWED` because
we couldn’t get that working for macros in public headers in GLib.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
=> xb-query-context: Only use G_ALIGNOF if GLib is new enough

src/xb-builder-source-ctx-private.h, src/xb-builder-source-ctx.c, src/xb-builder-source.c
As well as an input stream for reading the source, store a `GFile`
pointing to the on-disk file which backs the source, if possible.
This allows callers to load the source data directly from disk, which
may be more efficient than streaming it in, and will almost certainly be
more efficient than allocating a 128MB GBytes buffer and reading it all
at once. For example, a caller could memory map moderately sized files.
This adds new API, and breaks some internal API.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
=> xb-builder-source-ctx: Store a GFile for the source too

src/xb-self-test.c, src/xb-silo.c
When searching for non-ASCII this slows down the query by ~ x4 and so this is
an interim fix before we tokenize as part of the silo build.
=> Use g_str_match_string() for non-ASCII search queries

src/xb-silo.c
GFileMonitors currently need to be explicitly cancelled when they are
unreffed, otherwise they can deadlock due to the GLib-internal worker
thread also holding a strong reference to the monitor.
For full details, see: https://gitlab.gnome.org/GNOME/glib/-/issues/1941
Closes #59
=> xb-silo: Cancel the GFileMonitor before unreffing it

src/xb-machine.c, src/xb-opcode.c, src/xb-stack-private.h, src/xb-stack.c
Avoid heap-allocating it when it’s being used to run an `XbMachine`, as that happens 3 million times when starting gnome-software.
This reduces the time it takes to show the main window of gnome-software by 0.1s (from 1.1s to 1.0s). It reduces the number of `memset()` calls measured by callgrind from 27.4 million to 4.8 million.
No public API changes, so this should be OK to backport to stable distros if desired.
=> Improve performance of XbStack

src/meson.build
Fixes:
DEPRECATION: Library xmlb was passed to the libraries keyword argument of a
previous call to generate() method instead of first positional argument.
=> trivial: Fix a warning when used in a subproject

src/xb-builder.c, src/xb-silo.c
See the commit messages for details.
This is not required to fix the immediate issue in gnome-software (a workaround was committed in https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1422), but does tidy things up and make the behaviour more consistent.
Code which uses libxmlb should check what `GMainContext` is the thread default when calling `xb_builder_new()`, `xb_silo_new()`, `xb_builder_ensure()`, `xb_builder_compile()` or `xb_silo_watch_file()`.
=> Fix GMainContext issues with silo signals and file monitoring

meson_options.txt, src/meson.build
We don't need or want this debugging tool on embedded targets.
=> Use -Dcli=false to reduce the install size

src/xb-builder.c, src/xb-builder.h, src/xb-self-test.c
This is required for programs like fwupd to reject invalid (appended)
metainfo.xml files.
=> Add a flag to require the XbBuilderSource to have no siblings

src/libxmlb.map, src/xb-node.c, src/xb-node.h
Hi!
This adds the simplest iterator possible to iterate over all XbNode attributes (can only initialize and go forward). With having something like this, I can convert an XbNode into a libxml2 node using some really simple test code:
```c
static gboolean
as_transmogrify_xbnode_to_xmlnode (XbNode *xbn, xmlNode *lxn)
{
XbNodeIter attr_iter;
const gchar *attr_name;
const gchar *attr_value;
g_autoptr(GPtrArray) children = NULL;
g_return_val_if_fail (XB_IS_NODE (xbn), FALSE);
xmlNodeSetName (lxn,
(xmlChar*) xb_node_get_element (xbn));
xmlNodeAddContent (lxn,
(xmlChar*) xb_node_get_text (xbn));
xb_node_attr_iter_init (&attr_iter, xbn);
while (xb_node_attr_iter_next (&attr_iter, &attr_name, &attr_value))
xmlNewProp (lxn, (xmlChar*) attr_name, (xmlChar*) attr_value);
/* all children */
children = …
```
=> Add simple iterator for XbNode attributes

src/libxmlb.map, src/xb-node.c, src/xb-node.h
Hi!
This is the same style of iterator for XbNode children that ican now also be used for node attributes.
It is more efficient than using the `get_children()` method, and may be more obvious to use than the combination of `get_next()` and `get_child()` (while probably not being faster than those).
=> Add an iterator for XbNode children

src/xb-builder-node.c, src/xb-self-test.c
Hi!
I thought I was going crazy yesterday (and that's still a possibility...) but now I am pretty sure that XbBuilderNode was generating wrong XML the whole time with the tail being placed inside the node rather than after.
This patch should resolve that issue, please check if that's really the issue or rather me misunderstanding something ;-)
Cheers,
Matthias
=> Put tail after the node when exporting XbBuilderNode

src/xb-builder.c
Do not use the address of a pointer as this breaks reproducible builds.
Fixes https://github.com/hughsie/libxmlb/issues/110
Based on a patch by Roland Clobus <rclobus@rclobus.nl>, many thanks.
=> Ensure reproducible results when importing a node

src/xb-silo.c
We already ignore the GFile-default file prefix, but it's much clearer
to just ignore all hidden files.
Fixes https://github.com/hughsie/libxmlb/issues/117
=> Ignore all hidden files when using _WATCH_DIRECTORY

src/meson.build
`--version-script` isn't supported by the macOS linker and build fails with:
```
ld: unknown option: --version-script
```
Many thanks to @jtojnar for helping with this, with this fix libxmlb builds on x86_64-darwin now (I added you as a co-author hope you don't mind).
See also: https://github.com/GNOME/gcab/commit/14fe32b0759bf907303c9646e272c796d0bf7d37
=> build: fix building on macOS

src/xb-builder.c, src/xb-node.c, src/xb-self-test.c
This will only happen when using xb_node_get_child(xb_silo_get_root()).
Fixes https://github.com/hughsie/libxmlb/issues/120
=> Fix a crash for when the root tree has no children

src/xb-machine.c, src/xb-self-test.c, src/xb-tool.c
PVS: Suspicious access to element of 'values' array by a constant index inside a loop.
=> Fix dumping and exporting multiple files from the CLI

meson.build
The build script throw error with MSYS2 on Windows:
```
meson.build:117:20: ERROR: Unknown variable "prefix".
```
=> Update meson.build to fix compile issue

src/xb-machine.c
xb_machine_opcodes_optimize() is dominated by xb_stack_to_string() (as roughly 50% of the overhead). This equates to about .4% of discarded CPU usage on a GNOME Software search via GNOME Shell.
=> machine: avoid discarded xb_stack_to_string()

src/xb-machine.c, src/xb-silo.c
We don't want the penalty of tokenizing for the most common == operator.
=> trivial: Only tokenize when using ~= for the first time

src/xb-builder-source.c
Some system reports text/xml instead of application/xml as result of g_content_type_guess, in src/xb_common.c, line 73.
```
gchar *
xb_content_type_guess(const gchar *filename, const guchar *buf, gsize bufsz)
{
g_autofree gchar *content_type = NULL;
/* check for bad results, e.g. from Chrome OS */
content_type = g_content_type_guess(filename, buf, bufsz, NULL);    //Here
if (g_strstr_len(content_type, -1, "/") == NULL ||
g_strcmp0(content_type, "application/octet-stream") == 0 ||
g_strcmp0(content_type, "text/plain") == 0) {
/* magic */
if (bufsz > 0) {
if (xb_content_type_match(buf, bufsz, 0x0, "\x1f\x8b", 2))
return g_strdup("application/gzip");
if (xb_content_type_match(buf, bufsz, 0x0, "\xfd\x37\x7a\x58\x5a\x00", 6))
return g_strdup("application/x-xz");
if (xb_content_type_match(buf, …
```
=> Fixing the Assertion of MIME Types Used by Parser

src/xb-zstd-decompressor.c
This partially reverts 20eeebd4b385da1c7165cf3e9d94acd449d7a2bc, but instead moves the success check to after we update bytes_read and bytes_written.
Fixes https://github.com/fwupd/fwupd/issues/7060
=> Fix decompressing large zstd files, harder

src/xb-silo-query.c
They clearly transfer the ownership of the returned value to the caller.
=> trivial: Fix the return transfer of queries
